export const IPC_CHANNELS = {
  GET_ADB_STATUS: 'adb:get-status',
  GET_DEVICES: 'adb:get-devices',
  CONNECT_USB: 'adb:connect-usb',
  CONNECT_WIFI: 'adb:connect-wifi',
  PAIR_WIFI: 'adb:pair-wifi',
  DISCONNECT: 'adb:disconnect',
  START_LOGCAT: 'adb:start-logcat',
  STOP_LOGCAT: 'adb:stop-logcat',
  GET_PERFORMANCE: 'adb:get-performance',
  CAPTURE_PERFORMANCE_SNAPSHOT: 'adb:capture-performance-snapshot',
  START_PERFORMANCE_RECORDING: 'adb:start-performance-recording',
  READ_SNAPSHOT_IMAGE: 'performance:read-snapshot-image',
  EXPORT_PERFORMANCE_SESSION: 'performance:export-session',
  GET_PROCESSES: 'adb:get-processes',
  GET_ACTIVITY_STACK: 'adb:get-activity-stack',
  GET_NETWORK_REQUESTS: 'adb:get-network-requests',
  MIRROR_START: 'mirror:start',
  MIRROR_STOP: 'mirror:stop',
  MIRROR_STATUS: 'mirror:status',
  SELECT_APK_FILES: 'adb:select-apk-files',
  INSTALL_APK: 'adb:install-apk',
  UNINSTALL_APP: 'adb:uninstall-app',
  LIST_INSTALLED_PACKAGES: 'adb:list-installed-packages',
  LAUNCH_APP: 'adb:launch-app',
  FORCE_STOP_APP: 'adb:force-stop-app',
  SLEEP_DEVICE: 'adb:sleep-device',
  WAKE_DEVICE: 'adb:wake-device',
  UNLOCK_DEVICE: 'adb:unlock-device',
  REBOOT_DEVICE: 'adb:reboot-device',
  EXPORT_LOGS: 'log:export',
  LOG_ENTRY: 'log:entry',
  LOG_BATCH: 'log:batch',
  ADB_STATUS_CHANGED: 'adb:status-changed',
  DEVICE_CONNECTED: 'device:connected',
  DEVICE_DISCONNECTED: 'device:disconnected',
  DEVICE_LIST_CHANGED: 'device:list-changed',
} as const;

export type IpcChannelType = typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS];
